/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#afecff',
        secondary: '#aaccd7',
        'on-surface-variant': '#bfc8cc',
        'on-background': '#e2e2e8',
        error: '#ffb4ab',
        'inverse-primary': '#0b677a',
        'surface-dim': '#111318',
        surface: '#111318',
        'on-surface': '#e2e2e8',
        'on-secondary': '#11353e',
        outline: '#899296',
        'inverse-surface': '#e2e2e8',
        'surface-container-low': '#1a1c20',
        'primary-container': '#a0e9ff',
        'surface-bright': '#37393e',
        'surface-variant': '#333539',
        'on-secondary-container': '#98bbc6',
        'surface-container-highest': '#333539',
        'surface-container-high': '#282a2e',
        'on-primary-container': '#136b7e',
        'surface-tint': '#88d1e7',
        'surface-container': '#1e2024',
        'inverse-on-surface': '#2f3035',
        'on-primary': '#003641',
        tertiary: '#fffaf7',
        'tertiary-container': '#ffd998',
        background: '#111318',
        'outline-variant': '#3f484b',
        'surface-container-lowest': '#0c0e12',
        'on-error': '#690005',
        'secondary-container': '#2a4b55',
        'primary-fixed-dim': '#88d1e7',
        primary: '#f4fcff',
        'error-container': '#93000a',
        'secondary-fixed': '#c5e8f4',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        label: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
